export type Scholarship = {
  name: string;
  provider: string;
  amount: string;
  countries: string[];
  eligibility: string;
  deadline: string;
  link: string;
};

export const SCHOLARSHIPS: Scholarship[] = [
  {
    name: "Inlaks Shivdasani Foundation Scholarship",
    provider: "Inlaks Foundation",
    amount: "Up to $100,000",
    countries: ["USA", "UK", "Europe"],
    eligibility: "Indian nationals under 30, exceptional academic record",
    deadline: "February (annual)",
    link: "https://inlaksfoundation.org",
  },
  {
    name: "Tata Scholarship at Cornell University",
    provider: "Tata Trusts",
    amount: "Full tuition + fees",
    countries: ["USA"],
    eligibility: "Indian students admitted to Cornell undergrad with financial need",
    deadline: "Via Cornell financial aid",
    link: "https://financialaid.cornell.edu",
  },
  {
    name: "Aga Khan Foundation Scholarship",
    provider: "Aga Khan Foundation",
    amount: "Partial to full funding",
    countries: ["USA", "UK", "Canada", "Germany"],
    eligibility: "Academic excellence + financial need, developing countries",
    deadline: "March (annual)",
    link: "https://www.akdn.org/akf-scholarships",
  },
  {
    name: "Chevening Scholarship",
    provider: "UK Government (FCDO)",
    amount: "Full fees + living allowance",
    countries: ["UK"],
    eligibility: "2+ years work experience, return to India commitment",
    deadline: "November",
    link: "https://www.chevening.org",
  },
  {
    name: "Commonwealth Scholarship",
    provider: "Commonwealth Scholarship Commission",
    amount: "Full funding",
    countries: ["UK"],
    eligibility: "Indian nationals, postgraduate study",
    deadline: "October–December",
    link: "https://cscuk.fcdo.gov.uk",
  },
  {
    name: "Gates Cambridge Scholarship",
    provider: "Gates Foundation / Cambridge",
    amount: "Full funding for Cambridge",
    countries: ["UK"],
    eligibility: "Outstanding academics + leadership potential, any degree",
    deadline: "October (early round), January",
    link: "https://www.gatescambridge.org",
  },
  {
    name: "Rhodes Scholarship",
    provider: "Rhodes Trust",
    amount: "Full Oxford funding + stipend",
    countries: ["UK"],
    eligibility: "Age 18–24, exceptional academics + character + commitment",
    deadline: "August",
    link: "https://www.rhodeshouse.ox.ac.uk",
  },
  {
    name: "Fulbright-Nehru Master's Fellowships",
    provider: "US–India Educational Foundation",
    amount: "Full funding for USA",
    countries: ["USA"],
    eligibility: "Indian citizens, strong academics, 3 yrs work experience",
    deadline: "May",
    link: "https://www.usief.org.in",
  },
  {
    name: "DAAD Scholarship",
    provider: "German Academic Exchange Service",
    amount: "€934/month + travel",
    countries: ["Germany"],
    eligibility: "Indian students, Masters or PhD, above-average grades",
    deadline: "October–November",
    link: "https://www.daad.de",
  },
  {
    name: "Holland Scholarship",
    provider: "Dutch Ministry of Education",
    amount: "€5,000 (one-time)",
    countries: ["Netherlands"],
    eligibility: "Non-EU students, Bachelor's or Master's at Dutch institutions",
    deadline: "February–May (varies by university)",
    link: "https://www.studyinholland.nl",
  },
  {
    name: "Singapore International Graduate Award (SINGA)",
    provider: "A*STAR / NUS / NTU / SUTD",
    amount: "SGD 2,000/month + tuition",
    countries: ["Singapore"],
    eligibility: "PhD research, strong academic record",
    deadline: "January, June",
    link: "https://www.singa.a-star.edu.sg",
  },
  {
    name: "NUS Research Scholarship",
    provider: "National University of Singapore",
    amount: "SGD 2,500/month + tuition waiver",
    countries: ["Singapore"],
    eligibility: "PhD, strong research background",
    deadline: "Rolling",
    link: "https://nus.edu.sg",
  },
  {
    name: "Australia Awards Scholarships",
    provider: "Australian Government (DFAT)",
    amount: "Full tuition + living",
    countries: ["Australia"],
    eligibility: "Indian citizens, development-focused fields",
    deadline: "April",
    link: "https://www.australiaawardsindia.org",
  },
  {
    name: "University of Melbourne Graduate Research Scholarships",
    provider: "University of Melbourne",
    amount: "Tuition waiver + AUD 32,000/year",
    countries: ["Australia"],
    eligibility: "Outstanding research potential, PhD",
    deadline: "October",
    link: "https://scholarships.unimelb.edu.au",
  },
  {
    name: "Narotam Sekhsaria Foundation Scholarship",
    provider: "NS Foundation",
    amount: "Up to ₹20 lakhs (study abroad loan-scholarship)",
    countries: ["USA", "UK", "Canada", "Australia", "Singapore"],
    eligibility: "Indian students, merit-based, diverse fields",
    deadline: "March",
    link: "https://pg.nsfoundation.co.in",
  },
  {
    name: "JN Tata Endowment Loan Scholarship",
    provider: "JN Tata Endowment",
    amount: "₹5–10 lakhs",
    countries: ["USA", "UK", "Canada", "Australia"],
    eligibility: "Indian nationals, merit, any discipline",
    deadline: "February",
    link: "https://www.jntataendowment.org",
  },
  {
    name: "Azim Premji Foundation Scholarship",
    provider: "Azim Premji Philanthropic Initiatives",
    amount: "Full sponsorship",
    countries: ["India"],
    eligibility: "Strong academics, social sector orientation",
    deadline: "Rolling",
    link: "https://azimpremjiuniversity.edu.in",
  },
  {
    name: "ICCR Scholarship (Study in India)",
    provider: "Indian Council for Cultural Relations",
    amount: "Tuition + accommodation",
    countries: ["India"],
    eligibility: "Foreign nationals — not typically for Indian students outbound",
    deadline: "February",
    link: "https://a2ascholarships.iccr.gov.in",
  },
  {
    name: "Varun Behl Foundation Scholarship",
    provider: "Varun Behl Foundation",
    amount: "Partial",
    countries: ["USA"],
    eligibility: "Indian students with financial need, STEM focus",
    deadline: "March",
    link: "https://varungbehlfoundation.org",
  },
  {
    name: "Shastri Indo-Canadian Institute Scholarship",
    provider: "Shastri Institute",
    amount: "CAD 1,500–15,000",
    countries: ["Canada"],
    eligibility: "Indian students, research collaboration with Canadian institutions",
    deadline: "December",
    link: "https://www.shastriinstitute.org",
  },
];
